### ISSUE TITLE
Support Request: Prevent dropdown from closing when scrolling inside the dropdown on mobile

### ISSUE THREAD

**Issue by rangelke** [oferh/ng2-completer#206]
Due to a massive array, it's really massive. Although we want to show all possible items after typing in 3 characters, which results in a massive dropdown and is not so nice to look at. 

Using shadow piercing selecter I was able to change styling of the dropdown. 
```css
/deep/ .completer-dropdown {
    width: 32% !important;
    overflow-y: auto;
    overflow-x: hidden;
    height: 10rem;
}
```

The dropdown now shows a couple items and on a computer it's perfectly possible to scroll down in the dropdown. However on mobile, whenever you want to scroll down, it selects an item and closes the dropdown. Probably caused by the fact that `(selected: CompleterItem): void` emits an event when touching the screen trying to scroll down.
