### ISSUE TITLE
Dropup menu

### ISSUE THREAD

**Issue by tlorenzetti** [oferh/ng2-completer#350]
I would like to use the completer at the bottom of the page. Anyway, since the dropdown menu opens under the input field it is not completely visible. Is there a way to open the menu upward instead? Something like the `dropup` class in bootstrap [dropdowns](https://getbootstrap.com/docs/3.3/components/#dropdowns)

**Comment by oferh** [comment]
Hi,
not at the moment since movement and highlight only support dropdown

**Comment by tlorenzetti** [comment]
For those who are eventually interested, I implemented a workaround applying some styles. Maybe it's not the best solution, but it works for my purpose.
```css
ng2-completer {
    position: relative;
}
.completer-dropdown {
    bottom: 20px;
}
```
In this way the dropdown menu opens above the input field (offset of 20px in my case) and it eventually grows upward.
