### ISSUE TITLE
How to remove the clear input icon?

### ISSUE THREAD

**Issue by LuisJavierRT** [oferh/ng2-completer#446]
There is a way to remove the clear input icon? 

<img width="245" alt="Screen Shot 2020-02-20 at 7 09 31 PM" src="https://user-images.githubusercontent.com/14285679/74994914-026d8600-5415-11ea-9477-040976a9d4f1.png">

**Comment by MrNocTV** [comment]
@LuisJavierRT You can try this:
```css
/* clears the 'X' from Internet Explorer */
input[type='search']::-ms-clear,
input[type='search']::-ms-reveal {
    display: none;
    width: 0;
    height: 0;
}

/* clears the 'X' from Chrome */
input[type='search']::-webkit-search-decoration,
input[type='search']::-webkit-search-cancel-button,
input[type='search']::-webkit-search-results-button,
input[type='search']::-webkit-search-results-decoration {
    display: none;
}

```
